<template>
  <div
    class="
      bg-primary
      rounded-t-3xl
      mx-2
      px-5
      pt-5
      sm:px-10
      sm:pt-10
      mt-10
      "
  >
    <div
      class="
        w-full
        bg-[rgba(255,255,255,0.7)]
        rounded-t-3xl
        p-2
        sm:p-5
        "
    >
      <div
        class="
          container
          h-full
          mx-auto
          2xl:flex
          block
          "
      >
        <div
          class="
            sm:w-80
            text-primary
            flex-none
            flex
            items-center
            m-5
            lg:m-0
            lg:mr-5
          "
        >
          <div>
            <img class="w-3/5 sm:w-1/2" src="/logo.png" alt="logo"/>
            <span>หมาร้องโฮ่ง แมวร้องเหมียว นกร้องจิ๊บ ส่วนหนูร้องจิ๊ด</span>
          </div>
        </div>
        <div
          class="
            flex-auto
            lg:flex
            block
            mt-5
            2xl:mt-0
          "
        >
          <div
            class="
              text-primary
              flex-auto
              m-5
              lg:m-0
              lg:mr-5
              "
          >
            <span class="text-xl">Meet our team</span>
            <div 
              class="
                w-100
              "
            >

            </div>
          </div>
          <div
            class="
              bg-black
              flex-none
              rounded-xl
              sm:w-48
              m-5
              h-60
              text-white
              lg:m-0
              lg:ml-5
              "
          >
            <span>View Github</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
}
</script>

<style>
</style>